add application form
Hexlet/hexlet-interview pull request #19
Opened 2019-09-13 08:28 UTC by frontstall

Хотел добавить профессиии и уровни в виде массивов, чтобы итерировать в опции селекта, но не нашёл, где рендерится шаблон =\

2019-09-13 12:14 UTC, jougene commented
> Хотел добавить профессиии и уровни в виде массивов, чтобы итерировать в опции селекта, но не нашёл, где рендерится шаблон =\

https://github.com/Hexlet/hexlet-interview/blob/3cdbd9f6d08c2e05e17a1d3e9996a35cebaf1fc4/src/modules/request/request.controller.ts#L17

2019-09-13 13:37 UTC, jougene commented
Я добавил в ридми пункт по поводу того, что все тексты мы юзаем через файлы переводов.

2019-09-13 17:45 UTC, amshkv requested changes

2019-09-13 17:45 UTC, amshkv commented on views/request/new.pug
> +    .d-flex.pt-5
тут должен быть `.row`, а не `.d-flex`

2019-09-15 09:01 UTC, frontstall commented on views/request/new.pug
> +    .d-flex.pt-5
:heavy_check_mark:

2019-09-15 10:04 UTC, jougene commented on views/request/new.pug
> +        form
action - POST /request

2019-09-15 10:04 UTC, jougene commented on views/request/new.pug
> +            label(for='profession') В чём вы сильны
Давай как в ишью написано - на первое время сделаем теже профессии что и на хекслете.

2019-09-15 10:04 UTC, merged