change layout
Hexlet/hexlet-interview pull request #23
Opened 2019-09-15 14:35 UTC by frontstall

Заголовок рендерится всегда, содержимое - только если есть что рендерить. Поправил вёрстку.

2019-09-15 15:16 UTC, amshkv requested changes

2019-09-15 15:16 UTC, amshkv commented on views/request/index.pug
> +    .row.pt-5
если у нас одна колонка, то зачем нам `.row > .col`?

2019-09-15 15:16 UTC, amshkv commented on views/index.pug
> +        .col.d-flex
такой же вопрос

2019-09-15 15:16 UTC, amshkv commented on views/index.pug
> +        .col
ну и тут `.row > .col` похоже не к месту)

2019-09-16 09:03 UTC, merged

2019-09-16 09:03 UTC, jougene commented
thanks @frontstall