Add config module
Hexlet/hexlet-interview pull request #24
Opened 2019-09-16 15:55 UTC by grigori-gru

Все в одном получилось, тесты как-то странно работали, добавил асинки и последовательный запуск, иначе ничего не летит. Обратите внимание, что все development файлы добавил в игнор, каждый по своему хоть как стартует.

2019-09-16 16:16 UTC, grigori-gru commented
Я этот момент вообще не понял зачем:
```js
  async findAll(): Promise<any> {
    const all = await this.service.findAll();
    return {
      requests: [
        {
          username: 'Василий Пупкин',
          profession: 'Backend PHP developer',
          position: 'Junior',
        },
      ],
    };
  }

2019-09-16 17:12 UTC, jougene commented
Изменения касающиеся тестов в отдельный пр.

2019-09-16 17:12 UTC, jougene commented
Надо указать ссылку на issue

2019-09-16 22:04 UTC, jougene commented
А что с тестами было не так? Можно поподробнее?

2019-09-16 22:05 UTC, jougene commented
> Я этот момент вообще не понял зачем:
> 
> ```js
>   async findAll(): Promise<any> {
>     const all = await this.service.findAll();
>     return {
>       requests: [
>         {
>           username: 'Василий Пупкин',
>           profession: 'Backend PHP developer',
>           position: 'Junior',
>         },
>       ],
>     };
>   }
> ```

Это тестовые данные нужны были чтобы проверить отображение. Они отсюда уйдут.

2019-09-16 22:11 UTC, jougene requested changes

2019-09-16 22:11 UTC, jougene commented on test.env
> +DB_TYPE=sqlite
Для sqlite можно оставить только db_type и db_name - остальное можно убрать

2019-09-16 22:11 UTC, jougene commented on src/modules/config/config.module.ts
> +        `${process.env.NODE_ENV || 'development'}.env`,
Если мы меняем дефолтный .env - то надо не забыть поправить таргет setup в мейкфайле

2019-09-17 11:52 UTC, grigori-gru commented
У меня изменения в тестах вообще микроскопические. Твою логику создания отдельного файла  для тестов старта тестового app я учел, сам тоже так делаю. Смысл PR плодить? Понятно, что лучше разбить на атомарные задачи, но тут, если тесты вообще все вместе летели, зачем это нужно? Добавил еще dropSchema для тестового окружения.

2019-09-17 11:53 UTC, grigori-gru commented
Может `logging: ['error']` поставить для орм ? Для чего все логи с базы?

2019-09-17 12:12 UTC, jougene commented
> У меня изменения в тестах вообще микроскопические. Твою логику создания отдельного файла для тестов старта тестового app я учел, сам тоже так делаю. Смысл PR плодить? Понятно, что лучше разбить на атомарные задачи, но тут, если тесты вообще все вместе летели, зачем это нужно? Добавил еще dropSchema для тестового окружения.

Дело не том что они микроскопические или немикроскопические. Дело в том, что они не реашют конкретную задачу. Почему старые тесты падали ты не говоришь. (Хотя множество билдов в тревисе подтверждают что тесты НЕ падали.). Конкретный пулл реквест решает конкретное issue - ты его кстати сам создал. Так что давай ограничивать скоуп изменений, которые есть в пр, так проще смотреть, ревьюить и понимать - была ли решене issue в рамках pull request'a.

2019-09-17 12:18 UTC, grigori-gru commented
Я ж написал, они стартовали все вместе.

2019-09-17 12:19 UTC, grigori-gru commented
Я открыл рядом pr, там в 30 файлах изменения и 900 строк добавлено))

2019-09-17 12:35 UTC, grigori-gru commented
Зачем, кстати все валить в одну кучу в app.testing? В createTestingApp достаточно просто возвращать инициализированный app, к чему туда репы пихать?

2019-09-17 12:46 UTC, jougene commented
> Я ж написал, они стартовали все вместе.
> Он такую ошибку будет выдавать: `AlreadyHasActiveConnectionError: Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.`

Я запустил у себя тесты 10 раз - ни разу не наткнулся на такую проблему.

2019-09-17 12:47 UTC, jougene commented
> Зачем, кстати все валить в одну кучу в app.testing? В createTestingApp достаточно просто возвращать инициализированный app, к чему туда репы пихать?

Возможно да, это не лучшее принятое решение. Работа с БД предполагается почти в каждом тесте. Репозитории хочется иметь сразу, так что хочется, чтобы не нужно было создавать их в самих тестах, а они были сразу.

2019-09-17 12:48 UTC, jougene commented
> Зачем, кстати все валить в одну кучу в app.testing? В createTestingApp достаточно просто возвращать инициализированный app, к чему туда репы пихать?

Давай мы в пр по добавлению конфиг модуля не будем ревьюить другие части программы. Предлагаю здесь оставить ТОЛЬКО добавление config модуля, остальные вещи унести в отдельный пулл реквест с обоснование того, что не так.

2019-09-17 12:51 UTC, jougene commented
> Я открыл рядом pr, там в 30 файлах изменения и 900 строк добавлено))

Задача по добавлению аутентификации правда оказалась большой. Но если рассматривать ее с точки зрения фичи - то ее имеет мало смысла делать отдельными частями - там все связано логически. Ну и нужно иметь ввиду, что из 900 строк 420 - это package-lock

2019-09-17 13:10 UTC, grigori-gru commented
Хорошо, если такой порядок, то отдельный пулреквест сделаю на изменение тестов.

2019-09-17 13:20 UTC, jougene commented
> Хорошо, если такой порядок, то отдельный пулреквест сделаю на изменение тестов.

У нас не всегда получается его соблюдать - но мы должны к этому стремиться. ))

2019-09-17 13:22 UTC, jougene requested changes

2019-09-17 13:22 UTC, jougene commented on package.json
> +    "test": "jest --runInBand --detectOpenHandles --forceExit --verbose=false",
Это тоже в другой пр

2019-09-18 18:38 UTC, jougene approved these changes

2019-09-18 18:57 UTC, jougene commented
Thanks @grigori-gru

2019-09-18 18:58 UTC, merged

2019-09-18 20:44 UTC, jougene commented
Твой пр сломал релиз в прод.