Переход на postgress в dev и test среде.  (Closes #50)
Hexlet/hexlet-interview pull request #52
Opened 2019-09-25 10:02 UTC by mput

2019-09-26 11:07 UTC, jougene commented
Надо бы порешать конфликты

2019-09-27 10:24 UTC, jougene requested changes

2019-09-27 10:24 UTC, jougene commented on Makefile
> +	psql -p 15023 -h localhost -U test -d interview
psql тогда тоже надо добавить в ридми как зависимости

2019-09-27 10:24 UTC, jougene commented on src/modules/config/config.service.ts
> +      const envFileName = env === 'production' ? undefined : `${env}.env`;
странно стало выглядеть - выше проверка уже есть

2019-09-27 10:24 UTC, jougene commented on test/fixtures.loader.ts
> +  await connection.dropDatabase();
Вот прям дропать БД это что-то жестко. Надо бы сделать на транзакции и откате  транзакции в конце.

2019-09-27 10:33 UTC, mput commented on test/fixtures.loader.ts
> +  await connection.dropDatabase();
Хм, идея хорошая, пока не представляю как это сделать, почитаю доки.

2019-09-27 10:49 UTC, mput commented on src/modules/config/config.service.ts
> +      const envFileName = env === 'production' ? undefined : `${env}.env`;
Выше ты имеешь ввиду здесь: https://github.com/Hexlet/hexlet-interview/blob/b8d59cb50654dbb59ca20b7c33f1c8fe2ab5124c/src/ormconfig.ts#L4 ?
Этим комитом я убрал оттуда логику по выбору env файла. Во первых потому что он неправильно обрабатывал случай когда NODE_ENV undefined, во вторых потому что у нас выбор файла был размазан по трем разным местам. Теперь в одном, и там где это логичнее всего, в модуле конфигурации.

2019-09-27 11:26 UTC, mput commented on test/fixtures.loader.ts
> +  await connection.dropDatabase();
Если честно, очень плохо представляю как реализовать подобное. Решение в лоб стартовать транзакцию через: 
`  await connection.dropDatabase();                                                                      │
const queryRunner = connection.createQueryRunner(); `
в beforeEach естественно не работает.
Есть такой пакет: https://github.com/odavid/typeorm-transactional-cls-hooked , можно через него, но я не уверен на сколько это будет стабильно, и все равно нужно будет оборачивать каждый тест.
Предлагаю пока оставить мой вариант, вынести обертку тестов в транзакции в отдельный issue, чтобы это не тормозило дальнейший процесс.

2019-09-27 11:39 UTC, mput commented on Makefile
> +	psql -p 15023 -h localhost -U test -d interview
Сделал запуск консоли из докера, чтобы не плодить требования по зависимостям.

2019-09-27 11:53 UTC, jougene approved these changes

2019-09-27 11:53 UTC, merged

2019-09-27 11:54 UTC, mput commented on src/modules/config/config.service.ts
> +      const envFileName = env === 'production' ? undefined : `${env}.env`;
Ага, затупил, 9-ая строчка была лишней, удалил.