Mail verify
Hexlet/hexlet-interview pull request #55
Opened 2019-09-25 14:38 UTC by grigori-gru

Только нужно предыдущий pr слить с форматированием, иначе изменений слишком много.

2019-09-26 10:28 UTC, jougene commented
Предыдущий пр я слил. Но в следующий раз пры где смешано форматирование и решение задачи - приниматься не будут.

2019-09-26 11:04 UTC, jougene commented
Почему бы кстати не заиспользовать вот этот пакет - https://github.com/nest-modules/mailer

2019-09-26 11:23 UTC, jougene requested changes

2019-09-26 11:23 UTC, jougene commented on package.json
> +    "test:watch": "jest --watch --verbose=false",
Это для чего? Не выглядит особо полезным.

2019-09-26 11:23 UTC, jougene commented on src/db/migrations/1569401705190-update_users.ts
> +        name: 'token',
Давай назовем это не просто токен а как то более специфично. А то непонятно для чего нужен просто "токен"

2019-09-26 11:23 UTC, jougene commented on src/modules/auth/auth.controller.ts
> +    // !!TODO need correct redirect url
Думаю стоит сделать флеш сообщение с чем то вроде "На ваш емейл выслано письмо для подтверждения регистрации"

2019-09-26 11:23 UTC, jougene commented on src/modules/auth/auth.controller.ts
> +      throw new NotFoundException();
Что в таком случае покажется пользователю? Кажется нужно что-то подружелюбнее чем просто эксепшн

2019-09-26 11:23 UTC, jougene commented on src/modules/user/user.entity.ts
> +    this.token = uuidGenerate();
Противоестественно выглядит в этом методе

2019-09-26 11:23 UTC, jougene commented on src/modules/user/user.service.ts
> +  async verifyUser(user: User): Promise<void> {
если это уже user service, то в имени метода можно это (user) и не обозначать

2019-09-26 11:23 UTC, jougene commented on test/mocks/mailer.mock.ts
> +export const mailerServiceMock = {
Это стаб

2019-09-26 11:23 UTC, jougene commented on src/modules/mailer/mailer.service.ts
> +  // !!TODO mail sender will be here
Как бы без этого все остальное не имеет смысла.)

2019-09-26 19:13 UTC, grigori-gru commented on package.json
> +    "test:watch": "jest --watch --verbose=false",
Я это использую для вывода console.log в тестах, мне так удобно просто) глобально ничего не меняет. Если надо снести могу, без проблем

2019-09-26 19:16 UTC, grigori-gru commented on src/db/migrations/1569401705190-update_users.ts
> +        name: 'token',
Во, "token" мне как-то тоже не очень логичнымn кажется, может по смыслу запутать. Предложи какой-то вариант, что-то типа "verify_uuid" можно

2019-09-26 19:21 UTC, grigori-gru commented on src/modules/auth/auth.controller.ts
> +    // !!TODO need correct redirect url
С флэшами вообще ничего не делал, фронт вообще по этой таске надо кому-то отдельно отдать

2019-09-26 19:26 UTC, grigori-gru commented on src/modules/user/user.entity.ts
> +    this.token = uuidGenerate();
Я это сюда зря положил, конечно, там был вариант через декоратор автоматически генерить uuid, но в миграциях sqite ругался, что не может сгенерить

2019-09-26 19:31 UTC, grigori-gru commented on test/mocks/mailer.mock.ts
> +export const mailerServiceMock = {
Учитывая, что проверяю вызов в тесте и в дальнейшем могу изменить поведение  - mock.

2019-09-26 19:35 UTC, grigori-gru commented on src/modules/mailer/mailer.service.ts
> +  // !!TODO mail sender will be here
Конечно!) Но считаю, что сперва проще со всей структурой раскидаться в pr, а в абстракцию что-то закинуть это уже не проблема.

2019-09-26 19:35 UTC, grigori-gru commented on src/modules/auth/auth.controller.ts
> +      throw new NotFoundException();
Все, что с фронтом  лучше кому-то другому поручить

2019-09-26 19:36 UTC, grigori-gru commented on src/modules/user/user.service.ts
> +  async verifyUser(user: User): Promise<void> {
Ок, исправлю

2019-09-27 06:12 UTC, mput commented on src/modules/auth/auth.service.ts
> +      return null;
Нужно бы придумать некий механизм, как отличать разные проблемы при входе. Сейчас forbidden-exception.filter.ts обрабатывает все случаи одинаково.

2019-09-27 12:27 UTC, grigori-gru commented on package.json
> +    "test:watch": "jest --watch --verbose=false",
Оставлю, ок?

2019-09-27 12:33 UTC, jougene commented on package.json
> +    "test:watch": "jest --watch --verbose=false",
окей.

2019-09-27 12:34 UTC, jougene commented on src/db/migrations/1569401705190-update_users.ts
> +        name: 'token',
uuid не оч хорошо - это всегото алгоритм генерации уникальных значений. Давай confirmation_token

2019-09-27 12:48 UTC, grigori-gru commented on src/db/migrations/1569401705190-update_users.ts
> +        name: 'token',
Ок, тогда в таблице меняю, в остальных местах оставляю "token"

2019-09-27 12:58 UTC, jougene commented on src/db/migrations/1569401705190-update_users.ts
> +        name: 'token',
> в остальных местах оставляю "token"

2019-09-27 13:21 UTC, grigori-gru commented on src/modules/auth/auth.service.ts
> +      return null;
Можно код другой поставить ошибки

2019-09-27 13:23 UTC, grigori-gru commented on src/db/migrations/1569401705190-update_users.ts
> +        name: 'token',
Ты хочешь везде что ли `confirmationToken` ставить?

2019-09-27 13:27 UTC, grigori-gru commented on src/db/migrations/1569401705190-update_users.ts
> +        name: 'token',
Я сейчас в коммите скинул ниже

2019-09-27 13:30 UTC, grigori-gru commented
Тут же как-то можно закрывать обсуждения под решенными обсуждениями, а то когда такое количество - не очень удобно

2019-09-27 13:35 UTC, grigori-gru commented on test/mocks/mailer.mock.ts
> +export const mailerServiceMock = {
Кстати, если не брать в основу разделение на моки, стабы, спаи и еще какие-то виды заглушок, то всегда для большинства проще понимать, использование `mock` в название какого-то метода или сервиса. Для почти всех - всё это одно и то же

2019-09-27 15:23 UTC, jougene commented on src/db/migrations/1569401705190-update_users.ts
> +        name: 'token',
Да так норм

2019-09-27 15:23 UTC, jougene commented
> Тут же как-то можно закрывать обсуждения под решенными обсуждениями, а то когда такое количество - не очень удобно

зарезолвил почти все

2019-09-29 11:20 UTC, jougene commented
Надо порешать конфликты.

2019-09-30 09:18 UTC, jougene commented
Много еще тут делать? Или может есть вариант довести что-то до логического конца и разбить задачу на более мелкие? @grigori-gru

2019-09-30 09:23 UTC, grigori-gru commented
Можно весь фронт вынести отдельно

2019-09-30 09:23 UTC, grigori-gru commented
С почтой сегодня сделаю

2019-09-30 09:25 UTC, grigori-gru commented on src/modules/user/user.entity.ts
> +    this.token = uuidGenerate();
Здесь же я вынес в отдельный `BeforeInsert`

2019-09-30 10:14 UTC, mput commented
Тут же фронта вроде вообще быть не должно. Только флэш-сообщения. 
При регистрации - о том что сообщение о подтверждении было отправлено на почту.
При входе с не подтвержденным email - о том что необходимо подтвридить (и линк на повторную отправку).
При успешном подтверждении - редирект на главную в залогиненом состоянии, и флэш - что email подтвержден.

2019-09-30 14:26 UTC, grigori-gru commented
Добавил сервис для регистрации, не стал брать для нест пакет, он бы немного на уровне модулей структуры бы переделал, nodemailer итак простой как барабан. С фильтрами надо теперь немного переделать, может другой код ошибки добавим при отстутствие подтверждения по почте?

2019-09-30 15:02 UTC, grigori-gru commented
Либо вместо null внутри `validateUser` пробрасывать ошибку с текстом и на уровне фильтров уже возвращать нужное уведомление по сообщению об ошибке?

2019-09-30 16:49 UTC, mput commented
Я сделал подкласс от autherror, и отдельный фильтр на нее, посмотри в github.guard. Может так? Мне показалось лучше, чем через код ошибки деспетчировать.

2019-10-01 08:22 UTC, grigori-gru commented
Ну как? Принимаем?

2019-10-01 08:26 UTC, grigori-gru commented
Да можно либо User возвращать, либо {error: 'err_msg'} возвращать в `validate`, если ошибка, то прокидывать в `exception` и уже в фильтре разбирать. Но лучше отдельной issue

2019-10-01 09:00 UTC, jougene commented
Примем, когда не будет конфликтов.

2019-10-01 10:22 UTC, grigori-gru commented
Не понял, какие конфликты остались?

2019-10-01 10:28 UTC, jougene commented
> Не понял, какие конфликты остались?

![image](https://user-images.githubusercontent.com/13833179/65954783-53251800-e44f-11e9-8ea1-b84d331d4ce7.png)

2019-10-01 10:33 UTC, grigori-gru commented
Ок, сейчас.

2019-10-01 13:56 UTC, jougene commented
Подрубил вот это - https://devcenter.heroku.com/articles/mailgun. Надо сынтегрировать.

2019-10-01 13:58 UTC, jougene commented
энвы вот так будут называться - 
![image](https://user-images.githubusercontent.com/13833179/65968970-ab1e4780-e46c-11e9-8660-fa12d654d1f1.png)
их названия я поменять не могу.

2019-10-02 10:18 UTC, jougene requested changes

2019-10-02 10:18 UTC, jougene commented on src/modules/config/config.service.ts
> +export interface MailParams {
кажется второй интерфейс лишний

2019-10-02 12:09 UTC, merged