Интервьюер как foreign key User. Архивные интервью в основной таблице.
Hexlet/hexlet-interview pull request #60
Opened 2019-10-03 08:24 UTC by mput

2019-10-03 19:00 UTC, jougene requested changes

2019-10-03 19:00 UTC, jougene commented on src/db/migrations/1570024268340-add_interviewer_as_foreignkey.ts
> +      'ALTER TABLE "user" ALTER COLUMN "enabled" TYPE boolean USING CASE WHEN enabled=0 THEN FALSE ELSE TRUE END',
нам этот enabled не нужен вовсе - предлагаю убрать вообще

2019-10-03 19:00 UTC, jougene commented on src/db/migrations/1570024303371-seed_interwiews_to_main_table.ts
> +        state: 'happened',
давай стейт назовем `passed`

2019-10-03 19:00 UTC, jougene commented on src/modules/interview/interview.service.ts
> +      where: { state: 'happened' },
тут тоже `passed`

2019-10-03 19:00 UTC, jougene commented on src/modules/user/user.entity.ts
> +  archival: boolean;
archived лучше будет. 
![image](https://user-images.githubusercontent.com/13833179/66155764-0432da80-e629-11e9-958f-3d5fd095d08e.png)

2019-10-03 19:00 UTC, jougene commented on .gitignore
> +.vim/
https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

2019-10-03 19:00 UTC, jougene commented on .gitignore
> +Makefile.local
Это откуда и для чего - чем стандартный мейкфайл не устроил?

2019-10-03 21:19 UTC, mput commented on .gitignore
> +.vim/
Thanks!

2019-10-04 06:15 UTC, mput commented on src/db/migrations/1570024268340-add_interviewer_as_foreignkey.ts
> +      'ALTER TABLE "user" ALTER COLUMN "enabled" TYPE boolean USING CASE WHEN enabled=0 THEN FALSE ELSE TRUE END',
Я оставил, это все же такая стандартная фича, забанить юзера. Понятно, что нам скорее всего не пригодится, но пусть будет.

2019-10-04 06:22 UTC, mput commented
Исправил. 
Жду #61 чтобы убрать конфликты и починить тесты.

2019-10-04 09:46 UTC, merged