BadRequestExceptionFilter with render template as parameter. Validation errors.
Hexlet/hexlet-interview pull request #65
Opened 2019-10-08 07:21 UTC by mput

- **BadRequestExceptionFilter теперь принимает путь шаблона как параметр.** Instance BadRequestExceptionFilter должен передаваться в декоратор `@UseFilters()` для **каждого** контроллера который использует декоратор `@Body()` для валидации тела запроса.
 _(есть ощущение, что это не лучшее решение проблемы выбора шаблона, для рендеринга ошибки. Если кто то знает лучший - расскажите)_
- BadRequestExceptionFilter включает логику по генерации данных для отображения ошибок в формах.
- Формы `interview/new` & `user/new` теперь поддерживают отображение ошибок. 
- _Refactoring_ общие утилиты, такие как guards и filters перенесены в папку common, так как они используются из всех модулей, и нелогично их держать в папке модуля auth.

Скриншот формы с отображение ошибки:
![image](https://user-images.githubusercontent.com/1230663/66374426-a4835900-e9b3-11e9-9f53-ec29f5b60b9e.png)

2019-10-09 09:17 UTC, jougene requested changes

2019-10-09 09:17 UTC, jougene commented on src/common/filters/bad-request-exception.filter.ts
> +      (request as any).flash('error', i18n.__(`validation.${message}`));
странно выглядит, что мы проверяем пустой ли объект с ошибками и если пустой то показываем ошибку.

2019-10-09 09:17 UTC, jougene commented on src/common/filters/bad-request-exception.filter.ts
> +    this.logger.log(message);
Думаю что раз уж воткнули логгер, уместнее `this.logger.error`

2019-10-09 09:17 UTC, jougene commented on src/common/utils/view.helpers.ts
> +const prepareFormData = (data): any => data || { values: {}, errors: {} };
лучше типизировать, чтобы не передавать всякую дичь.

2019-10-09 09:17 UTC, jougene commented on test/controllers/interview.controller.test.ts
> +        description: "I'm definityly good developer",
очепятка

2019-10-09 09:17 UTC, jougene commented on views/mixins/forms.pug
> +  - const value = formdata.values[property] ? formdata.values[property] : '';
почему нельзя просто `formdata.values[property] || ''`

2019-10-09 09:17 UTC, jougene commented on views/interview/new.pug
> +            small: __('interview.form.professsion-description')
Странно называть часть данных функции по имени класса бутстрапа. Это наверное что-то типа `field-description`

2019-10-09 09:17 UTC, jougene commented on views/interview/new.pug
> +            as: 'textarea',
не увидел использования `as`

2019-10-10 14:17 UTC, jougene requested changes

2019-10-10 14:17 UTC, jougene commented on src/common/filters/bad-request-exception.filter.ts
> +      response.render(this.template, { formdata: new FormData(values) });
можно объединить с ретурном

2019-10-10 14:17 UTC, jougene commented on src/common/filters/bad-request-exception.filter.ts
> +      (request as any).flash('error', errors);
any больше неактуально

2019-10-10 14:17 UTC, jougene commented on src/common/utils/form-data.ts
> +  constructor(public readonly values: object = {}, public readonly errors: ValidationError[] = []) {}
`values: {[key: string]: string}` наверное. От просто object мало толку

2019-10-10 14:17 UTC, jougene commented on src/common/utils/form-data.ts
> +    const { constraints } = this.getPropertyError(property) as ValidationError;
вот чтобы приведение типов не делать надо 
```
const a = this.getPropertyError(property)
if (!a) {
  return [];
}
const { constraints }  = a;
```
Просто так тс не уверен что при вызове `this.getPropertyError` ты не мутируешь само property

2019-10-10 14:27 UTC, mput commented on src/common/filters/bad-request-exception.filter.ts
> +      response.render(this.template, { formdata: new FormData(values) });
Имеешь ввиду написать return response.render(this.template, { formdata: new FormData(values) })?
Вопервых будет ошибка типа, потому что метод catch возвращает void, а во вторых будет сбивать толку, сейчас понятно что return - это просто выход из функции.

2019-10-10 14:27 UTC, mput commented on src/common/filters/bad-request-exception.filter.ts
> +      (request as any).flash('error', errors);
Исправленно при мердж коммите.

2019-10-10 14:35 UTC, mput commented on src/common/utils/form-data.ts
> +    const { constraints } = this.getPropertyError(property) as ValidationError;
Сенкс, я его уже по разному крутил, не подумал про мутацию.

2019-10-10 14:48 UTC, jougene commented on src/common/filters/bad-request-exception.filter.ts
> +      response.render(this.template, { formdata: new FormData(values) });
ok

2019-10-10 14:49 UTC, jougene approved these changes

2019-10-10 14:50 UTC, jougene commented
Thanks a lot @mput

2019-10-10 14:50 UTC, merged