Интерфейс управления интервью. (closes #27)
Hexlet/hexlet-interview pull request #70
Opened 2019-10-16 13:56 UTC by mput

![Снимок1](https://user-images.githubusercontent.com/1230663/66925905-c9bc3b00-f035-11e9-9731-dc01c1b01753.JPG)
![Снимок2](https://user-images.githubusercontent.com/1230663/66925906-ca54d180-f035-11e9-8c99-242b0b882970.JPG)
![Снимок3](https://user-images.githubusercontent.com/1230663/66925907-ca54d180-f035-11e9-938c-fedd0e3f8e5e.JPG)
![Снимок4](https://user-images.githubusercontent.com/1230663/66925908-caed6800-f035-11e9-9971-21114d66231a.JPG)

2019-10-17 06:45 UTC, amshkv commented on views/interview/assignment.pug
> +              div.mr-4
div не нужен, если есть класс или id

2019-10-17 06:46 UTC, amshkv commented on views/interview/assignment.pug
> +              div.mt-2
div не нужен, если есть класс или id

2019-10-17 12:08 UTC, jougene requested changes

2019-10-17 12:08 UTC, jougene commented on locales/ru.json
> +    "canceled_interviews": "Отменные интервью"
Отмененные

2019-10-17 12:08 UTC, jougene commented on locales/ru.json
> +    "manage_interviews": "Управлять интервью",
Управление интервью

2019-10-17 12:08 UTC, jougene commented on locales/ru.json
> +    "date must be a valid ISO 8601 date string": "Необходимо указать в формату ISO 8601",
че это за формат даты (человеку непонятно будет)

2019-10-17 12:08 UTC, jougene commented on src/bootstrap.ts
> +    if (req.user) {
а с какой целью ифочка такая появилась?

2019-10-17 12:08 UTC, jougene commented on src/common/validators/custom.validators.ts
> +export function IsOptional(validationOptions?: ValidationOptions): (object: object, propertyName: string) => void {
![image](https://user-images.githubusercontent.com/13833179/67005657-caafa400-f0eb-11e9-9f34-c7dc763c68e1.png)
А чем собственно встроенное не подошло?

2019-10-17 12:08 UTC, jougene commented on src/modules/interview/interview.service.ts
> +    const entity = { ...interviewApplicationDto, interviewee: user, state: 'application' };
это должно быть дефолтным полем в модели

2019-10-17 12:08 UTC, jougene commented on src/modules/interview/interview.service.ts
> +    return this.interviewRepo.save({
мы должны прийти к тому что мы просто вызываем `interview.coming()` по имени стейта и дальше уже логика в модели.

2019-10-17 12:08 UTC, jougene commented on test/controllers/interview.admin.controller.test.ts
> +describe('#interview', () => {
managing interview

2019-10-17 12:08 UTC, jougene commented on test/controllers/interview.controller.test.ts
> +    const numberOfInterviewsBefore = (await userRepo.findOne(kozma.id, {
грязно. хочется конечно чтобы мы могли делать вот так - `kozma.interviews.length` или как то так, а не заново искать юхера в бд, только для прогрузки релейшнов

2019-10-17 12:08 UTC, jougene commented on test/controllers/interview.controller.test.ts
> +    expect(reloadedUser!.interviews.length).toEqual(numberOfInterviewsBefore + 1);
вообще конечно привязываться просто к количеству интервью, не уточняя что это именно заявки будет очень странно.

2019-10-17 12:08 UTC, jougene commented on test/controllers/interview.admin.controller.test.ts
> +  it('assign interview should fail', async () => {
должно зафейлиться по какой причине? Большой тест, который проверяет какую то ветку из сценария когда что-то пошло не так.

2019-10-17 12:08 UTC, jougene commented on test/controllers/interview.admin.controller.test.ts
> +  it('show all interviews', async () => {
давай разделим на 4 теста для каждого стейта. Щас в одном месте очень много.

2019-10-17 12:08 UTC, jougene commented on test/controllers/auth.controller.test.ts
> +    const res = await request(app.getHttpServer())
а чем прошлый варик не устраивал? джест вроде умеет нормально с промисами работать. И не приходиться городить еще переменных.

2019-10-17 12:08 UTC, jougene commented on src/modules/interview/interview.entity.ts
> +  // TODO: maybe need enum type? and set db column?
Да, тут нужен енум, вот только в бд енума не надо.

2019-10-17 12:09 UTC, mput commented on src/common/validators/custom.validators.ts
> +export function IsOptional(validationOptions?: ValidationOptions): (object: object, propertyName: string) => void {
Для него пустая строка != отсутствие значения.

2019-10-18 08:51 UTC, mput commented on test/controllers/auth.controller.test.ts
> +    const res = await request(app.getHttpServer())
Прошлый вариант не работал:
```
  it('login with valid credentials', async () => {
    return request(app.getHttpServer())
      .post('/auth/sign_in')
      .send(existingUserAuthInfo)
      .expect(HttpStatus.FOUND)
      .then(res => {
        request(app.getHttpServer())
          .get('/interview/new')
          .set('Cookie', res.header['set-cookie'])
          .expect(HttpStatus.OK);
      });
  });
```
Jest не ждет завершение вложенного промиса. Можно было конечно done передать в тест и вызвать его после последнего expect, но мой вариант лучше.

2019-10-18 08:52 UTC, mput commented on src/modules/interview/interview.entity.ts
> +  // TODO: maybe need enum type? and set db column?
Я сходу не нашел как typescript enum замапить на sting в бд. Но я не особо пробовал, посмотрю еще раз.

2019-10-18 08:53 UTC, mput commented on locales/ru.json
> +    "canceled_interviews": "Отменные интервью"
Просто туда саммые лучшие заявки попадают. )

2019-10-18 08:54 UTC, mput commented on locales/ru.json
> +    "date must be a valid ISO 8601 date string": "Необходимо указать в формату ISO 8601",
Когда будет датапикер - человек этого никогда не увидит.

2019-10-18 08:54 UTC, mput commented on src/bootstrap.ts
> +    if (req.user) {
Баг.

2019-10-23 07:11 UTC, mput commented on src/modules/interview/interview.entity.ts
> +  // TODO: maybe need enum type? and set db column?
Сделал.

2019-10-23 07:12 UTC, mput commented on test/controllers/interview.controller.test.ts
> +    expect(reloadedUser!.interviews.length).toEqual(numberOfInterviewsBefore + 1);
Согласен, но это за пределами области моего PR, а он и так громадный получился.

2019-10-23 22:08 UTC, merged